### ISSUE TITLE
Where is the Attack_Flow_builder.zip?

### ISSUE THREAD

**Issue by rchungts** [center-for-threat-informed-defense/attack-flow#101]
This page https://center-for-threat-informed-defense.github.io/attack-flow/builder/ takes me to this repo and the link said that if I don't want to use docker, I can download the Attack_Flow_builder.zip from the release page, but I don't see that file. Can you provide one?

**Comment by mehaase** [comment]
Apologies for the oversight! I just uploaded the 2.0.1 release zip. Please take another look.
