### ISSUE TITLE
Attack Builder: Bad STIX property name 'patter_version' in Indicator SDO

### ISSUE THREAD

**Issue by juancerezo** [center-for-threat-informed-defense/attack-flow#123]
Hi. There is a little error that may impact with STIX integration. The property "patter**n**_version" is implemented as "patter_version".

I was going to propose a change with a pull request but I don't know if it would have an impact on the flows already built. I hope you can fix this bug.

![image](https://github.com/center-for-threat-informed-defense/attack-flow/assets/7447739/bf8c156d-f9da-4f0c-92ce-558602b43f28)

https://github.com/center-for-threat-informed-defense/attack-flow/blob/7904d44ff755e8b3672a85d72f0848a61327edfa/src/attack_flow_builder/src/assets/configuration/builder.config.ts#L337C12-L337C82

**Comment by mehaase** [comment]
Thank you for pointing this out, we'll get that fixed this week. 

After the fix is released, existing attack flows will show a blank Pattern Version that needs to be filled in again. I apologize for the inconvenience.
