### ISSUE TITLE
Linkage to normative MITRE STIX Objects

### ISSUE THREAD

**Issue by JasonKeirstead** [center-for-threat-informed-defense/attack-flow#31]
Currently there is a "reference" field which may link to a ATT&CK ID, but there is no way to link to the normative MITRE STIX objects for ATT&CK. A field or relationship should be added to that one can create this linkage in some way, because there is currently no way to look up the STIX object for an ATT&CK technique ID programatically.

**Comment by mehaase** [comment]
@JasonKeirstead In the Attack Flow v2 data model we now support referencing upstream ATT&CK STIX objects. We are working on adding an autocomplete to make this feature easier to use, but the data model and builder support are in place now.
