### ISSUE TITLE
Re-orient Trees

### ISSUE THREAD

**Issue by lcarson-2002** [center-for-threat-informed-defense/attack-flow#49]
In AFD under your browser there's no way to re-orient the tree. While simple ATT&CK Flows are not an issue, complex ones become very cumbersome and a significant challenge to work with via the browser and keeping it organized. Adding a function to sort or re-organize the tree in order to better group the branches and leaves would help a lot.

Alternatively, have you considered using [Modelio](https://www.modelio.org/) or some other Open source modelling software that supports tree organizing? That might be more sustainable for the long run.

**Comment by mehaase** [comment]
Is this the same as #46?
