### ISSUE TITLE
Text input is for the Attack Flow UI is reversed

### ISSUE THREAD

**Issue by OpalSec** [center-for-threat-informed-defense/attack-flow#52]
Attempting to type input to any of the fields results in the string being entered in reverse. E.g. typing "Initial Access" causes it to appear as:
![image](https://user-images.githubusercontent.com/33176069/199654938-050b48bb-f481-4770-9f9e-082a503d7ea8.png)

This isn't happening anywhere else in my OS or browser, so I can only assume this is a behaviour of the platform. If so, is there a way to disable this, or is this a bug somehow?

**Comment by xtheorycrafter** [comment]
Are you doing this on Safari?Sent from my iPhoneOn 3 Nov 2022, at 13:48, OpalSec ***@***.***> wrote:﻿
Attempting to type input to any of the fields results in the string being entered in reverse. E.g. typing "Initial Access" causes it to appear as:

This isn't happening anywhere else in my OS or browser, so I can only assume this is a behaviour of the platform. If so, is there a way to disable this, or is this a bug somehow?

**Comment by OpalSec** [comment]
No, this was via Firefox on a Windows Desktop.

**Comment by xtheorycrafter** [comment]
This behaviour is also replicated and seen on Safari. Looks like a bug of sorts related to the “technique id” field for me at least. Sent from my iPhoneOn 3 Nov 2022, at 14:11, OpalSec ***@***.***> wrote:﻿
No, this was via Firefox on a Windows Desktop.

**Comment by mehaase** [comment]
Thanks for the report, we will look into it.

**Comment by bmarg** [comment]
I also had this problem with the Name and Description fields using the online UI and Firefox 106.0.5 (64-bit) on Ubuntu 20.04.5 LTS.  I tried using the docker image locally (from ghcr), same browser/OS, same problem.  Downloaded the zip version, same problem.

Online version same problem on Firefox 105.0.1 (64-bit) and Safari 16.1 on macOS Monterey 12.6.1.  Online version appears to work OK using Chrome Version 107.0.5304.110 (Official Build) (x86_64) on macOS Monterey 12.6.1.

**Comment by bmarg** [comment]
Chrome Version 107.0.5304.110 (Official Build) (64-bit) on Ubuntu seems to work ok also.

**Comment by lcarson-2002** [comment]
I'm seeing the same thing (reverse text) on macOS, I downloaded Builder 2.0.0 and tried opening the Index file on both Safari and FireFox. Current revs of both.
