### ISSUE TITLE
Add ATT&CK Technique auto-complete

### ISSUE THREAD

**Issue by OpalSec** [center-for-threat-informed-defense/attack-flow#60]
Adding auto-complete for the technique ID field of Action objects would help immensely, as it not only makes it easier to cite Techniques, but also ensures they're consistent and not subject to typos.

Being able to add multiple Techniques to a single Action object would also be helpful - though I understand if your view is that this isn't in keeping with the design intent of this project. 

It would be useful for my particular use case, though. See below for an example:

![image](https://user-images.githubusercontent.com/33176069/211987930-c27843ad-1364-49b6-9335-c9c002f4207b.png)

In visualising a long and complex intrusion, breaking each Technique into its own Action object would result in a sprawling diagram that would be hard to navigate.

My preference is to use the Name field to describe distinct stages of the intrusion, elaborating in the Description field while also inserting the relevant Technique IDs. In doing so I can condense multi-staged attack paths into more compact diagrams, broken up by milestones in the intrusion.

**Comment by mehaase** [comment]
Thank you for suggesting this. It is in our backlog and will be included in a release in the next 2 months.

**Comment by initstring** [comment]
Hi @mehaase ,

Thanks for your work on such a cool tool! I am also really interested in this feature. Is it still planned for release?

Thanks so much.
