### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by OpalSec** [center-for-threat-informed-defense/attack-flow#61]
The ability to perform keyword searches of afb diagrams is essential, especially for larger attack chains.

At a minimum, being able to search by key fields/objects such as Technique ID, Asset, Tool or Malware objects would be immensely useful.

**Comment by mehaase** [comment]
Great idea -- we will add this to our backlog!

**Comment by mehaase** [comment]
@OpalSec this feature is now live in the 2.1 release. Thank you for suggesting it!

<img width="1469" alt="Screenshot 2023-08-31 at 9 34 22 AM" src="https://github.com/center-for-threat-informed-defense/attack-flow/assets/320904/23fb4d01-f541-4437-9f6d-49212e978d55">
